####
GET http://0.0.0.0:5000/

###
POST http://0.0.0.0:5000/api/trackings
Authorization: Bearer __AUTH_TOKEN__
Content-Type: application/json

{}

###
POST http://0.0.0.0:5000/api/interaction 
Authorization: Bearer __AUTH_TOKEN__
Content-Type: application/json

{"title": "title", "image": "image"}