name: CI

on:
  push:
    branches: [ master, develop, feature/set-up-gitHub-actions-workflow-2 ]
  pull_request:
    branches: [ master, develop, feature/set-up-gitHub-actions-workflow-2 ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest pytest-cov black isort pylint

    - name: Check code formatting with Black
      run: black . --check

    - name: Check import sorting with isort
      run: isort . --check-only --diff

    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics --max-line-length=88 --extend-ignore=E203

    - name: Lint with pylint
      run: |
        pylint **/*.py

    - name: Run tests with pytest
      env:
        MONGODB_URI: mongodb://localhost:27017/test_db
        REDIS_URL: redis://localhost:6379/0
      run: |
        pytest --cov=. --cov-report=xml

    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true